using K9.DataAccessLayer.Models;

namespace K9.WebApplication.ViewModels
{
    public class HealthQuestionnaireViewModel
    {
        public HealthQuestionnaire HealthQuestionnaire { get; set; }
        public Protocol AutoGeneratedProtocol { get; set; }
    }
}