// <auto-generated />
namespace K9.DataAccessLayer.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IngredientIsHygroscopic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IngredientIsHygroscopic));
        
        string IMigrationMetadata.Id
        {
            get { return "202212180402538_IngredientIsHygroscopic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
