// <auto-generated />
namespace K9.DataAccessLayer.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddHealthQuestionnaire : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHealthQuestionnaire));
        
        string IMigrationMetadata.Id
        {
            get { return "202311100324312_AddHealthQuestionnaire"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
