// <auto-generated />
namespace K9.DataAccessLayer.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditConsultantOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditConsultantOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202404081037100_EditConsultantOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
