using K9.DataAccessLayer.Models;
using K9.WebApplication.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace K9.WebApplication.Services
{
    public interface IHealthQuestionnaireService : ICacheableService
    {
        HealthQuestionnaire GetHealthQuestionnaireForUser(int userId);
        HealthQuestionnaire GetHealthQuestionnaireForClient(int clientId);
        void Save(HealthQuestionnaire model);
        GeneticProfileMatchedItemsViewModel GetGeneticProfileMatchedItems(int id);
        List<Protocol> GetGeneticProfileMatchedProtocols(int clientId);
        Protocol GetAutoGeneratedProtocolFromGeneticProfile(int clientId);
        Protocol GetAutoGeneratedProtocolFromGeneticProfile(HealthQuestionnaire hq);
        void AutoGenerateProtocolFromGeneticProfile(int clientId);
        void AutoGenerateProtocolFromGeneticProfile(HealthQuestionnaire hq);
        Task AutoGenerateProtocolFromGeneticProfileAsync(HealthQuestionnaire hq);
    }
}