//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K9.Globalisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Glossary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Glossary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K9.Globalisation.Glossary", typeof(Glossary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AMPK enzyme is the master metabolic switch in each of your cells. When AMPK levels increase you get an energy boost, blood glucose is regulated, insulin sensitivity improves, reduced triglycerides, and increased fat-burning in mitochondria. The metabolism of the whole organism becomes considerably more efficient.
        /// </summary>
        public static string AMPK {
            get {
                return ResourceManager.GetString("AMPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A substance that is able to protect the body from oxidaitve stress (from free radicals) either by neutralising the radical or by protecting tissues, or both..
        /// </summary>
        public static string Antioxidant {
            get {
                return ResourceManager.GetString("Antioxidant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blood–brain barrier protects against circulating toxins or pathogens that could cause brain infections, while at the same time allowing vital nutrients to reach the brain..
        /// </summary>
        public static string BloodBrainBarrier {
            get {
                return ResourceManager.GetString("BloodBrainBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The major stress hormone of the body. In excess, cortisol can result int he breakdown of tissues, resulting in degenerative disease..
        /// </summary>
        public static string Cortisol {
            get {
                return ResourceManager.GetString("Cortisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free radicals result from oxidation in cells and damage tissues in the body. They are implicated in many types of age-related diseases..
        /// </summary>
        public static string FreeRadicals {
            get {
                return ResourceManager.GetString("FreeRadicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peptide hormone that stimulates growth, cell reproduction, and cell regeneration in humans and other animals. It is thus important in human development. GH also stimulates production of IGF-1 and increases the concentration of glucose and free fatty acids..
        /// </summary>
        public static string HumanGrowthHormone {
            get {
                return ResourceManager.GetString("HumanGrowthHormone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organelles of cells responsible for producing all of our ATP (cellular energy).
        /// </summary>
        public static string Mitochondria {
            get {
                return ResourceManager.GetString("Mitochondria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relating to the &apos;mitochondria&apos;:the organelles of cells responsible for producing all of our ATP (cellular energy).
        /// </summary>
        public static string Mitochondrial {
            get {
                return ResourceManager.GetString("Mitochondrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulates the growth of new mitochondria and the repair of existing ones..
        /// </summary>
        public static string Mitochondriogenesis {
            get {
                return ResourceManager.GetString("Mitochondriogenesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAD+ mediates the production of the energy our cells need to function and survive, fueling enzymes key in repairing DNA damage. As we age, this indispensable molecule progressively declines..
        /// </summary>
        public static string NAD {
            get {
                return ResourceManager.GetString("NAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The generation of new neurons.
        /// </summary>
        public static string Neurogenesis {
            get {
                return ResourceManager.GetString("Neurogenesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pigments that form in the brain that are similar to the melanin pigment in the skin..
        /// </summary>
        public static string Neuromelanins {
            get {
                return ResourceManager.GetString("Neuromelanins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nootropics can help to improve memory, boost learning ability, enhance mood and assist overall brain function and health..
        /// </summary>
        public static string Nootropic {
            get {
                return ResourceManager.GetString("Nootropic", resourceCulture);
            }
        }
    }
}
