//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K9.Globalisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Glossary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Glossary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("K9.Globalisation.Glossary", typeof(Glossary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AMPK enzyme is the master metabolic switch in each of your cells. When AMPK levels increase you get an energy boost, blood glucose is regulated, insulin sensitivity improves, reduced triglycerides, and increased fat-burning in mitochondria. The metabolism of the whole organism becomes considerably more efficient.
        /// </summary>
        public static string AMPK {
            get {
                return ResourceManager.GetString("AMPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A substance that is able to protect the body from oxidaitve stress (from free radicals) either by neutralising the radical or by protecting tissues, or both..
        /// </summary>
        public static string Antioxidant {
            get {
                return ResourceManager.GetString("Antioxidant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces anxiety.
        /// </summary>
        public static string Anxiolytic {
            get {
                return ResourceManager.GetString("Anxiolytic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adenosine triphosphate, also known as ATP, is a molecule that carries energy within cells. It is the main energy currency of the cell..
        /// </summary>
        public static string ATP {
            get {
                return ResourceManager.GetString("ATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A potent neurotrophin that stimulates the genesis of new neurons in the brain is referred to as neurogenesis. BDNF is implicated in neuroplasticity, learning, memory and higher thinking..
        /// </summary>
        public static string BDNF {
            get {
                return ResourceManager.GetString("BDNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blood–brain barrier protects against circulating toxins or pathogens that could cause brain infections, while at the same time allowing vital nutrients to reach the brain..
        /// </summary>
        public static string BloodBrainBarrier {
            get {
                return ResourceManager.GetString("BloodBrainBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The major stress hormone of the body. In excess, cortisol can result int he breakdown of tissues, resulting in degenerative disease..
        /// </summary>
        public static string Cortisol {
            get {
                return ResourceManager.GetString("Cortisol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRP is a protein secreted mostly by cells in the liver in response to a variety of inflammatory cytokines. CRP plays important roles in inflammatory processes including by altering pathways involved in apoptosis, phagocytosis, nitric oxide release and production of cytokines. Elevated CRP is a reliable marker of chronic inflammation..
        /// </summary>
        public static string CReactiveProtein {
            get {
                return ResourceManager.GetString("CReactiveProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A major neurotransmitter of the catecholamine family, implicated in pleasure, focus, motivation, memory, movement, mood, blood vessel function, planning and more..
        /// </summary>
        public static string Dopamine {
            get {
                return ResourceManager.GetString("Dopamine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free radicals result from oxidation in cells and damage tissues in the body. They are implicated in many types of age-related diseases..
        /// </summary>
        public static string FreeRadicals {
            get {
                return ResourceManager.GetString("FreeRadicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GABA is the main inhibitory neurotransmitter produced in the body. It helps to countr excessive neural excitement. GABA is implicated in mood, sleep, stress, anxiety, speech, cognition, memory, focus, blood pressure and more..
        /// </summary>
        public static string GABA {
            get {
                return ResourceManager.GetString("GABA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GABA is the main excitatory neurotransmitter produced in the body. It excites neurons and is implicated in memory, concentration, mood, cellular energy production, neuroplasticity and the growth and development of the brain..
        /// </summary>
        public static string Glutamate {
            get {
                return ResourceManager.GetString("Glutamate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peptide hormone that stimulates growth, cell reproduction, and cell regeneration in humans and other animals. It is thus important in human development. GH also stimulates production of IGF-1 and increases the concentration of glucose and free fatty acids..
        /// </summary>
        public static string HumanGrowthHormone {
            get {
                return ResourceManager.GetString("HumanGrowthHormone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organelles of cells responsible for producing all of our ATP (cellular energy).
        /// </summary>
        public static string Mitochondria {
            get {
                return ResourceManager.GetString("Mitochondria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relating to the &apos;mitochondria&apos;:the organelles of cells responsible for producing all of our ATP (cellular energy).
        /// </summary>
        public static string Mitochondrial {
            get {
                return ResourceManager.GetString("Mitochondrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulates the growth of new mitochondria and the repair of existing ones..
        /// </summary>
        public static string Mitochondriogenesis {
            get {
                return ResourceManager.GetString("Mitochondriogenesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAD+ mediates the production of the energy our cells need to function and survive, fueling enzymes key in repairing DNA damage. As we age, this indispensable molecule progressively declines..
        /// </summary>
        public static string NAD {
            get {
                return ResourceManager.GetString("NAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The generation of new neurons.
        /// </summary>
        public static string Neurogenesis {
            get {
                return ResourceManager.GetString("Neurogenesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pigments that form in the brain that are similar to the melanin pigment in the skin..
        /// </summary>
        public static string Neuromelanins {
            get {
                return ResourceManager.GetString("Neuromelanins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuroplasticity or brain plasticity is the inherent ability of the brain to adapt and change in reaction to internal and external stimuli. Your brain can change its functions and even its physical structure to react to inputs coming in from events, experiences, thoughts, and even human emotions..
        /// </summary>
        public static string Neuroplasticity {
            get {
                return ResourceManager.GetString("Neuroplasticity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chemical messenger used by the nervous system to send messages between nerve cells. .
        /// </summary>
        public static string Neurotransmitter {
            get {
                return ResourceManager.GetString("Neurotransmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nootropics can help to improve memory, boost learning ability, enhance mood and assist overall brain function and health..
        /// </summary>
        public static string Nootropic {
            get {
                return ResourceManager.GetString("Nootropic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A major neurotransmitter of the catecholamine family, implicated in focus, blood pressure, mood, sleep healthy stress response and more..
        /// </summary>
        public static string Norepinephrine {
            get {
                return ResourceManager.GetString("Norepinephrine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage to tissues and cells caused by free radicals, which is implicated in many chronic, degenerative diseases..
        /// </summary>
        public static string OxidativeStress {
            get {
                return ResourceManager.GetString("OxidativeStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A neurotransmitter that plays a role in sleep, appetite, learning, memory, mood, sexual function and more..
        /// </summary>
        public static string Serotonin {
            get {
                return ResourceManager.GetString("Serotonin", resourceCulture);
            }
        }
    }
}
